using System;
using System.Collections.Generic;
using Microsoft.Data.Sqlite;

namespace HackersVoca2006Data
{
    public static class Database
    {
        // 데이터베이스 초기화
        public static void InitializeDatabase()
        {
            using (SqliteConnection db = new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                string tableCommand = "CREATE TABLE IF NOT EXISTS Vocabularies (" +
                    "ID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    "Day INTEGER NOT NULL, " +
                    "Eng NVARCHAR(128) NOT NULL, " +
                    "Kor1 NVARCHAR(128) NOT NULL, " +
                    "Kor2 NVARCHAR(128) NULL, " +
                    "Kor3 NVARCHAR(128) NULL)";

                SqliteCommand createTable = new SqliteCommand(tableCommand, db);

                createTable.ExecuteReader();

                db.Close();

                // 단어 추가 (메인 데이터)
                AddVoca(1, "apt", "~하는 경향이 있는", "적당한", null);
                AddVoca(1, "astonish", "놀라게 하다", null, null);
                AddVoca(1, "chronically", "만성적으로", null, null);
                AddVoca(1, "daub", "흠뻑 칠하다", null, null);
                AddVoca(1, "domain", "지역, 영토", "분야, 영역", null);
                AddVoca(1, "enthusiastic", "열성적인", null, null);
                AddVoca(1, "extend", "(어떤 거리까지) 걸쳐 있다", "확장하다, 늘리다", null);
                AddVoca(1, "feat", "업적", null, null);
                AddVoca(1, "fulfill", "성취하다", "만족시키다", null);
                AddVoca(1, "give over to", "헌신하다, 바치다", null, null);
                AddVoca(1, "heavy", "무거운; 고된", null, null);
                AddVoca(1, "hibernation", "동면", null, null);
                AddVoca(1, "illusion", "착각, 오해", null, null);
                AddVoca(1, "intrigue", "(주의•관심을) 끌다", "음모를 꾸미다", null);
                AddVoca(1, "luxuriant", "무성한, 풍부한", null, null);
                AddVoca(1, "magnitude", "정도, 크기", null, null);
                AddVoca(1, "maintain", "주장하다", "지속하다", null);
                AddVoca(1, "monitor", "조사하다", null, null);
                AddVoca(1, "outbreak", "(전염병 등의) 만연, 창궐", "폭발", null);
                AddVoca(1, "periodically", "주기적으로", null, null);
                AddVoca(1, "release", "해방시키다", "뿜다, 방출하다", "(묶인 것을) 풀다");
                AddVoca(1, "rendering", "연주, 공연", null, null);
                AddVoca(1, "renowned", "유명한", null, null);
                AddVoca(1, "reproduce", "복제하다", "번식하다", null);
                AddVoca(1, "rugged", "울퉁불퉁한", null, null);
                AddVoca(1, "self-sufficent", "자급자족하는, 제힘으로 살아가는", null, null);
                AddVoca(1, "speculative", "이론적인", "사색적인, 깊이 생각하는", null);
                AddVoca(1, "stimulate", "자극하다, 격려하다", null, null);
                AddVoca(1, "subordinate", "종속적인", null, null);
                AddVoca(1, "torrential", "격렬한", null, null);
                AddVoca(2, "address", "주소", "강연", null);
                AddVoca(2, "assume", "맡다", "~인 척하다", "~라고 생각하다, 추측히다");
                AddVoca(2, "attain", "도달하다", "성취하다, 이루다", null);
                AddVoca(2, "boast", "자랑하다", null, null);
                AddVoca(2, "capacity", "용적", "능력", null);
                AddVoca(2, "cede", "양도하다, 포기하다", null, null);
                AddVoca(2, "decline", "거절하다", "하락하다, 쇠퇴하다", null);
                AddVoca(2, "desert", "버리다", null, null);
                AddVoca(2, "disassemble", "분해하다", null, null);
                AddVoca(2, "dispose", "배치하다, 배열하다", null, null);
                AddVoca(2, "dispose of", "처리하다", null, null);
                AddVoca(2, "erode", "침식하다, 부식되다", null, null);
                AddVoca(2, "fairly", "꽤", "공정하게", null);
                AddVoca(2, "glossy", "빛나는, 광택이 나는", null, null);
                AddVoca(2, "grounds", "근거, 이유", null, null);
                AddVoca(2, "hallmark", "특징", null, null);
                AddVoca(2, "ideal", "이상적인, 전형의", "관념적인, 추상적인", null);
                AddVoca(2, "inhabit", "거주하다", null, null);
                AddVoca(2, "laborious", "근면한", null, null);
                AddVoca(2, "linger", "남다", "꾸물거리다, 질질 끌다", null);
                AddVoca(2, "loathe", "혐오하다", null, null);
                AddVoca(2, "mimic", "모방하다", null, null);
                AddVoca(2, "model", "견본", null, null);
                AddVoca(2, "observe", "관찰하다; 알아채다", "준수하다", null);
                AddVoca(2, "plentiful", "풍부한", null, null);
                AddVoca(2, "preoccupied", "몰두한", null, null);
                AddVoca(2, "property", "자산", "특성", null);
                AddVoca(2, "recurring", "되풀이되는", null, null);
                AddVoca(2, "rooted", "뿌리 깊은, 정착한", null, null);
                AddVoca(2, "thoroughly", "철저히, 완전히", null, null);
                AddVoca(3, "afford", "주다", null, null);
                AddVoca(3, "announce", "공포하다", null, null);
                AddVoca(3, "a wide range of", "다양한", null, null);
                AddVoca(3, "chance", "가능성; 기회", null, null);
                AddVoca(3, "chart", "(지도 등을) 작성하다", null, null);
                AddVoca(3, "engage", "약속하다", "예약하다", "고용하다");
                AddVoca(3, "esteem", "존경하다, 중하게 여기다", null, null);
                AddVoca(3, "evidence", "증거; 징후", null, null);
                AddVoca(3, "fertile", "비옥한", null, null);
                AddVoca(3, "generate", "발생시키다", null, null);
                AddVoca(3, "innate", "타고난", null, null);
                AddVoca(3, "invaluable", "매우 귀중한", null, null);
                AddVoca(3, "irreparable", "돌이킬 수 없는", null, null);
                AddVoca(3, "maxim", "격언; 행동 원칙", null, null);
                AddVoca(3, "object", "항의하다", "목적", null);
                AddVoca(3, "outstanding", "뛰어난", "미결제의", null);
                AddVoca(3, "patron", "후원자", "고객", null);
                AddVoca(3, "predominate", "우세하다, 지배력을 갖다", null, null);
                AddVoca(3, "previous", "이전의", null, null);
                AddVoca(3, "premise", "전제", null, null);
                AddVoca(3, "primitive", "원시적인", "기본적인", null);
                AddVoca(3, "proficiency", "능숙함", null, null);
                AddVoca(3, "proposition", "제안", null, null);
                AddVoca(3, "questionable", "의심스러운", null, null);
                AddVoca(3, "rife with", "가득 찬, 수없이 많은", null, null);
                AddVoca(3, "shield", "보호하다", null, null);
                AddVoca(3, "solitary", "외딴, 고독한", null, null);
                AddVoca(3, "stick", "달라붙다, 고수하다", null, null);
                AddVoca(3, "sitmulus", "자극, 격려", null, null);
                AddVoca(3, "stir", "자극하다", null, null);
                AddVoca(3, "taboo", "금기", null, null);
                AddVoca(3, "thrive", "번성하다", null, null);
                AddVoca(3, "vagary", "예측 불허의 변화, 변덕", null, null);
                AddVoca(3, "wane", "감소하다, 쇠퇴하다", null, null);
                AddVoca(3, "view", "견해, 의견", "간주하다", null);
                AddVoca(4, "achieve", "성취하다", null, null);
                AddVoca(4, "anchor", "고정시키다", "닻", null);
                AddVoca(4, "attribute", "~의 탓으로 돌리다", "특성", null);
                AddVoca(4, "brisk", "활기 있는", null, null);
                AddVoca(4, "codify", "(체계적으로) 정리하다", null, null);
                AddVoca(4, "consummate", "뛰어난; 완전한", null, null);
                AddVoca(4, "descent", "하강", "혈통, 기원", null);
                AddVoca(4, "disseminate", "퍼뜨리다", null, null);
                AddVoca(4, "earn", "획득하다", null, null);
                AddVoca(4, "emergence", "출현, 부상", null, null);
                AddVoca(4, "facilitate", "용이하게 하다", null, null);
                AddVoca(4, "fervent", "열정적인", null, null);
                AddVoca(4, "fine", "미세한, 섬세한; 가느다란", null, null);
                AddVoca(4, "frivolous", "사소한", null, null);
                AddVoca(4, "giant", "거인", null, null);
                AddVoca(4, "golden age", "황금 시대, 전성기", null, null);
                AddVoca(4, "grasp", "붙잡다", "이해하다, 파악하다", null);
                AddVoca(4, "hamstrung", "무력한; 불구의", null, null);
                AddVoca(4, "haphazard", "되는대로의, 우연의", null, null);
                AddVoca(4, "incidental", "중요하지 않은; 우연한", null, null);
                AddVoca(4, "initiate", "시작하다", null, null);
                AddVoca(4, "make up", "창작하다, 창안하다", null, null);
                AddVoca(4, "manifold", "가지각색의", null, null);
                AddVoca(4, "obliterate", "제거하다", null, null);
                AddVoca(4, "period", "시대", null, null);
                AddVoca(4, "proceed", "나아가다", null, null);
                AddVoca(4, "procure", "얻다", null, null);
                AddVoca(4, "professional", "전문적인", null, null);
                AddVoca(4, "redundancy", "여분; 장황", null, null);
                AddVoca(4, "responsible", "책임이 있는", null, null);
                AddVoca(4, "sharp", "날카로운, 예리한", "급격한", null);
                AddVoca(4, "supplement", "보충하다", "추가, 부가", null);
                AddVoca(4, "suspend", "연기하다", "중지하다", "매달다");
                AddVoca(4, "tailored", "맞추어진", null, null);
                AddVoca(5, "aimlessly", "목적 없이", null, null);
                AddVoca(5, "ally", "~와 동맹하다, 연합하다", null, null);
                AddVoca(5, "anonymous", "익명의", null, null);
                AddVoca(5, "anticipate", "예견하다", null, null);
                AddVoca(5, "archaic", "원시적인; 구식의", null, null);
                AddVoca(5, "asset", "자질, 자산", "이점, 장점", null);
                AddVoca(5, "behavior", "행동", null, null);
                AddVoca(5, "ceaseless", "끊임없는", null, null);
                AddVoca(5, "change", "변화시키다", null, null);
                AddVoca(5, "confederacy", "연합, 동맹", null, null);
                AddVoca(5, "cut", "절단하다", null, null);
                AddVoca(5, "disturbance", "동요, 혼란", null, null);
                AddVoca(5, "elucidate", "명료하게 하다", null, null);
                AddVoca(5, "encroachment", "침범", null, null);
                AddVoca(5, "entice", "유혹하다", null, null);
                AddVoca(5, "equivocally", "애매하게", null, null);
                AddVoca(5, "exterminate", "근절하다", null, null);
                AddVoca(5, "fortify", "강화하다", null, null);
                AddVoca(5, "formerly", "이전에", null, null);
                AddVoca(5, "immunity", "면제", null, null);
                AddVoca(5, "improve", "개선하다", null, null);
                AddVoca(5, "in retrospect", "되돌아보면, 회상하면", null, null);
                AddVoca(5, "lose sight of", "잊다", null, null);
                AddVoca(5, "nuts and bolts", "기본", null, null);
                AddVoca(5, "permit", "허락하다", null, null);
                AddVoca(5, "radical", "근본적인", "급진적인", null);
                AddVoca(5, "rarely", "드물게, 좀처럼 ~않는", null, null);
                AddVoca(5, "sparse", "빈약한, 부족한", null, null);
                AddVoca(5, "sting", "얼얼하다, 쓰리다", null, null);
                AddVoca(5, "support", "지지하다", "부양하다", null);
                AddVoca(5, "tangible", "실질적인", null, null);
                AddVoca(5, "tolerate", "견디다", null, null);
                AddVoca(5, "train", "~로 향하게 하다", null, null);
                AddVoca(5, "unambiguous", "명확한", null, null);
                AddVoca(5, "virtually", "사실상", "거의", null);
                AddVoca(5, "wary", "조심(경계)하는", null, null);
                AddVoca(5, "wealth", "풍부함", null, null);
                AddVoca(5, "wiggle", "이리저리 흔들다", null, null);
                AddVoca(6, "agile", "민첩한", null, null);
                AddVoca(6, "ample", "넓은", "충분한", null);
                AddVoca(6, "arbitrarily", "임의로", null, null);
                AddVoca(6, "attest", "입증하다", null, null);
                AddVoca(6, "break with", "관계를 끊다", null, null);
                AddVoca(6, "brightness", "빛", null, null);
                AddVoca(6, "conjure", "불러내다, 상기시키다", "간청하다", null);
                AddVoca(6, "contrive", "고안해내다", null, null);
                AddVoca(6, "correspondence", "일치", "(편지로 하는) 통신", null);
                AddVoca(6, "durable", "지속적인", null, null);
                AddVoca(6, "dwarf", "난쟁이", null, null);
                AddVoca(6, "enigmatic", "알기 어려운", null, null);
                AddVoca(6, "extinct", "멸종된", null, null);
                AddVoca(6, "fabricate", "만들어내다", null, null);
                AddVoca(6, "flake", "파편", null, null);
                AddVoca(6, "harm", "손해", null, null);
                AddVoca(6, "innocent", "결백한", null, null);
                AddVoca(6, "in the course of", "~동안에", null, null);
                AddVoca(6, "in vain", "헛되이", null, null);
                AddVoca(6, "inconsequential", "하찮은, 사소한", null, null);
                AddVoca(6, "leave", "떠나다", null, null);
                AddVoca(6, "liken", "비유하다", null, null);
                AddVoca(6, "literally", "실제로", null, null);
                AddVoca(6, "moderate", "온건한", null, null);
                AddVoca(6, "prolong", "연장하다", null, null);
                AddVoca(6, "purify", "정화하다, 깨끗이 하다", null, null);
                AddVoca(6, "resonable", "이치에 맞는", null, null);
                AddVoca(6, "refined", "정제된", null, null);
                AddVoca(6, "retain", "유지(보유)하다", null, null);
                AddVoca(6, "scarce", "드문; 부족한", null, null);
                AddVoca(6, "scope", "범위", null, null);
                AddVoca(6, "shabby", "초라한", null, null);
                AddVoca(6, "short-lived", "단기간의", null, null);
                AddVoca(6, "solidify", "결속시키다", null, null);
                AddVoca(6, "substantial", "튼튼한", "상당한", null);
                AddVoca(6, "vacant", "텅 빈", null, null);
                AddVoca(6, "wizened", "시든, 주름진", null, null);
                AddVoca(6, "zone", "지역", null, null);
                AddVoca(7, "abolish", "폐지하다", null, null);
                AddVoca(7, "adage", "속담, 금언", null, null);
                AddVoca(7, "aesthetic", "미적인", null, null);
                AddVoca(7, "affect", "~에 영향을 미치다", "~인 체하다", null);
                AddVoca(7, "alteration", "변경", null, null);
                AddVoca(7, "amenity", "편의 시설", null, null);
                AddVoca(7, "approximately", "대략", null, null);
                AddVoca(7, "artisan", "숙련공", null, null);
                AddVoca(7, "bear", "운반하다", "산출하다, 생기게 하다", "(무게를) 지탱하다, 견디다");
                AddVoca(7, "bountiful", "풍부한", null, null);
                AddVoca(7, "constituent", "구성하는, 구성 요소의", null, null);
                AddVoca(7, "dispute", "논쟁하다", "논쟁", null);
                AddVoca(7, "faculty", "능력", null, null);
                AddVoca(7, "field", "분야", null, null);
                AddVoca(7, "guiltless", "결백한", null, null);
                AddVoca(7, "influx", "유입", null, null);
                AddVoca(7, "inundate", "물에 잠기게 하다", null, null);
                AddVoca(7, "lexicon", "어휘", null, null);
                AddVoca(7, "lure", "유혹하다", null, null);
                AddVoca(7, "mixture", "혼합(물)", null, null);
                AddVoca(7, "mount", "오르다", "증가하는", null);
                AddVoca(7, "mundane", "평범한", null, null);
                AddVoca(7, "nearly", "거의", null, null);
                AddVoca(7, "outstrip", "능가하다, 뛰어나다", null, null);
                AddVoca(7, "pertinent", "관련된, 적절한", null, null);
                AddVoca(7, "preclude", "그만두게 하다, 막다", null, null);
                AddVoca(7, "refrain", "삼가다, 중단하다", null, null);
                AddVoca(7, "roughly", "대략", null, null);
                AddVoca(7, "semblance", "외관", "유사한", null);
                AddVoca(7, "sophisticated", "복잡한; 정교한", null, null);
                AddVoca(7, "stage", "단계", null, null);
                AddVoca(7, "thick", "뻑뻑한", null, null);
                AddVoca(7, "thus", "따라서", null, null);
                AddVoca(7, "tiny", "작은", null, null);
                AddVoca(7, "verge", "경계, 찰나", null, null);
                AddVoca(8, "abort", "중단하다", null, null);
                AddVoca(8, "acquire", "얻다", null, null);
                AddVoca(8, "affection", "애정", null, null);
                AddVoca(8, "agree", "동의하다", null, null);
                AddVoca(8, "alert", "경계하는", "경고하는", null);
                AddVoca(8, "allure", "(마음을) 끌다, 유혹하다", null, null);
                AddVoca(8, "amplify", "늘리다", null, null);
                AddVoca(8, "arid", "매마른", null, null);
                AddVoca(8, "ascribe", "~의 탓으로 돌리다", null, null);
                AddVoca(8, "barge", "배", null, null);
                AddVoca(8, "compansate", "보상하다; 보충하다; 상쇄하다", null, null);
                AddVoca(8, "configure", "~의 형체로 만들다", null, null);
                AddVoca(8, "drastic", "과격한, 극단적인", null, null);
                AddVoca(8, "embarrass", "무안케 하다", null, null);
                AddVoca(8, "focus", "집중하다", null, null);
                AddVoca(8, "function", "기능, 역할", "기능하다", null);
                AddVoca(8, "gathering", "수집; 모임", null, null);
                AddVoca(8, "haul", "끌어당기다", null, null);
                AddVoca(8, "immediate", "인접한", null, null);
                AddVoca(8, "increase", "확대하다", null, null);
                AddVoca(8, "loom", "어렴풋이 나타나다", null, null);
                AddVoca(8, "overtax", "지나치게 과세하다", null, null);
                AddVoca(8, "paradox", "모순", null, null);
                AddVoca(8, "pervasive", "퍼지는", null, null);
                AddVoca(8, "pleasing", "마음에 드는, 기분 좋은", null, null);
                AddVoca(8, "primary", "근본적인", null, null);
                AddVoca(8, "proper", "적당한", null, null);
                AddVoca(8, "recur", "재발하다", null, null);
                AddVoca(8, "save for", "~을 제외하고", null, null);
                AddVoca(8, "serve", "소용이 되다, 도움이 되다", null, null);
                AddVoca(8, "simulate", "흉내 내다; 가장하다", null, null);
                AddVoca(8, "speck", "얼룩", "소량", null);
                AddVoca(8, "strive", "노력하다", null, null);
                AddVoca(8, "suppose", "가정하다", null, null);
                AddVoca(8, "surprise", "놀라게 하다", null, null);
                AddVoca(8, "treat", "다루다, 대하다", null, null);
                AddVoca(8, "undertake", "(책임•역할을) 맡다; 착수하다", null, null);
                AddVoca(8, "variant", "변형", null, null);
                AddVoca(9, "abandon", "그만두다, 버리다", null, null);
                AddVoca(9, "antidote", "치료법", null, null);
                AddVoca(9, "at hand", "사용 가능한", null, null);
                AddVoca(9, "bear in mind", "명심하다", null, null);
                AddVoca(9, "boost", "증대시키다", null, null);
                AddVoca(9, "conspicuous", "뚜렷한", null, null);
                AddVoca(9, "critical", "중요한", "위험한", "비평의");
                AddVoca(9, "discriminate", "식별하다", null, null);
                AddVoca(9, "dorsal", "등(부분)의", null, null);
                AddVoca(9, "eliminate", "제거하다", null, null);
                AddVoca(9, "fuse", "녹다, 녹이다", null, null);
                AddVoca(9, "hinterland", "배후지, 오지", null, null);
                AddVoca(9, "in earnest", "진지한", "진지하게", null);
                AddVoca(9, "laden", "(짐을) 실은", null, null);
                AddVoca(9, "lumber", "판재, 재목", null, null);
                AddVoca(9, "mirror", "반영하다", null, null);
                AddVoca(9, "mutual", "상호 간의; 공동의", null, null);
                AddVoca(9, "obtainable", "손에 넣을 수 있는", null, null);
                AddVoca(9, "patch", "수선하다", "작은 부분, 지역", null);
                AddVoca(9, "protest", "항의하다", null, null);
                AddVoca(9, "recall", "회상하다", null, null);
                AddVoca(9, "reflection", "반영", null, null);
                AddVoca(9, "regain", "~을 되찾다", null, null);
                AddVoca(9, "reinforce", "강화하다", null, null);
                AddVoca(9, "relevant", "관련된, 적절한", null, null);
                AddVoca(9, "reminisce", "추억하다", null, null);
                AddVoca(9, "route", "길", null, null);
                AddVoca(9, "secrete", "분비하다", null, null);
                AddVoca(9, "semiarid", "반건조한", null, null);
                AddVoca(9, "soothe", "진정시키다, 완화하다", null, null);
                AddVoca(9, "stay", "머무르다", null, null);
                AddVoca(9, "surplus", "나머지, 잔여", null, null);
                AddVoca(9, "toothed", "들쑥날쑥한", null, null);
                AddVoca(9, "transform", "변형시키다", null, null);
                AddVoca(9, "unbalanced", "균형을 잃은", null, null);
                AddVoca(9, "uniformly", "균일하게", null, null);
                AddVoca(9, "utilitarian", "실용적인", null, null);
                AddVoca(9, "variety", "다양성", "종류", null);
                AddVoca(9, "wonderful", "놀라운", null, null);
                AddVoca(10, "advantage", "이익", null, null);
                AddVoca(10, "arise from", "~에서 기인하다", null, null);
                AddVoca(10, "barrier", "장애물, 장벽", null, null);
                AddVoca(10, "betray", "배신히다", null, null);
                AddVoca(10, "bind", "묶다", null, null);
                AddVoca(10, "blur", "흐리게 하다", null, null);
                AddVoca(10, "circumvent", "우회하다", null, null);
                AddVoca(10, "clumsy", "서투른", null, null);
                AddVoca(10, "commence", "시작하다", null, null);
                AddVoca(10, "conduct", "행동", "(빛•열 등을) 전도하다", null);
                AddVoca(10, "conserve", "보존하다", null, null);
                AddVoca(10, "contradiction", "모순", null, null);
                AddVoca(10, "culminate", "~로 끝나다", null, null);
                AddVoca(10, "delineate", "윤곽을 그리다", null, null);
                AddVoca(10, "donation", "기부(금), 기증(물)", null, null);
                AddVoca(10, "embark on", "시작하다", null, null);
                AddVoca(10, "foundation", "기초", null, null);
                AddVoca(10, "fundamental", "근본적인", null, null);
                AddVoca(10, "handful", "소량, 소수", null, null);
                AddVoca(10, "height", "정상, 절정", null, null);
                AddVoca(10, "identical", "동일한", null, null);
                AddVoca(10, "impediment", "장애", null, null);
                AddVoca(10, "justify", "(정당성을) 증명하다", null, null);
                AddVoca(10, "lament", "슬퍼하다, 애도하다", null, null);
                AddVoca(10, "microorganism", "미생물", null, null);
                AddVoca(10, "origin", "발생, 근원", null, null);
                AddVoca(10, "peculiarity", "특성", null, null);
                AddVoca(10, "physical", "물질의", "육체의", null);
                AddVoca(10, "predict", "예측하다", null, null);
                AddVoca(10, "progress", "발전", null, null);
                AddVoca(10, "scoop", "긁어모으다", null, null);
                AddVoca(10, "score", "얻다", "악보, 악곡", null);
                AddVoca(10, "scrap", "파편", null, null);
                AddVoca(10, "singularly", "각별히", null, null);
                AddVoca(10, "skilled", "숙련된", null, null);
                AddVoca(10, "stem from", "~에서 유래하다", null, null);
                AddVoca(10, "subsidize", "후원하다", null, null);
                AddVoca(10, "unanimity", "(만장)일치", null, null);
                AddVoca(11, "account", "기술(記述)", "계좌", null);
                AddVoca(11, "alloy", "혼합하다", null, null);
                AddVoca(11, "barely", "거의 ~않다", null, null);
                AddVoca(11, "carry on", "~을 계속하다", null, null);
                AddVoca(11, "cohesion", "결속", null, null);
                AddVoca(11, "coincide", "동시에 일어나다", "의견이 일치하다", null);
                AddVoca(11, "colossal", "거대한", null, null);
                AddVoca(11, "considerable", "중요한", "상당한", null);
                AddVoca(11, "converge", "한데 모이다", null, null);
                AddVoca(11, "conviction", "신념", null, null);
                AddVoca(11, "covet", "갈망하다", null, null);
                AddVoca(11, "defect", "결점", null, null);
                AddVoca(11, "defection", "변절, 탈당", "결함, 부족", null);
                AddVoca(11, "dull", "지루한", null, null);
                AddVoca(11, "endeavor", "노력하다, 애쓰다", null, null);
                AddVoca(11, "flock", "무리, 떼", null, null);
                AddVoca(11, "grant", "주다", null, null);
                AddVoca(11, "hustle", "서두르다", "밀다", null);
                AddVoca(11, "intermediate", "중간의", null, null);
                AddVoca(11, "intolerant", "옹졸한, 편협한", null, null);
                AddVoca(11, "kind", "친절한, 인정 많은", "유형, 종류", null);
                AddVoca(11, "limit", "경계, 한계", "제한하다", null);
                AddVoca(11, "margin", "가장자리", null, null);
                AddVoca(11, "militia", "시민군", null, null);
                AddVoca(11, "moreover", "게다가", null, null);
                AddVoca(11, "necessary", "필수적인", null, null);
                AddVoca(11, "obstruct", "막다, 방해하다", null, null);
                AddVoca(11, "on the spot", "즉시", null, null);
                AddVoca(11, "partial", "편파적인", "불완전한; 부분적인", null);
                AddVoca(11, "placid", "평온한", null, null);
                AddVoca(11, "porosity", "구멍; 다공성", null, null);
                AddVoca(11, "reform", "개정하다, 개선하다", null, null);
                AddVoca(11, "rigid", "단단한, 뻣뻣한", "엄격한", null);
                AddVoca(11, "scarcity", "부족, 결핍", null, null);
                AddVoca(12, "adaptable", "융통성 있는, 적응성 있는", null, null);
                AddVoca(12, "adhesion", "달라붙음, 부착", null, null);
                AddVoca(12, "blame", "비난하다", null, null);
                AddVoca(12, "chaotic", "무질서한", null, null);
                AddVoca(12, "comprehand", "이해하다", null, null);
                AddVoca(12, "decided", "분명한; 단호한", null, null);
                AddVoca(12, "displace", "대체하다", null, null);
                AddVoca(12, "enclose", "에워싸다", null, null);
                AddVoca(12, "entail", "~을 수반하다", null, null);
                AddVoca(12, "excel", "능가하다, 빼어나다", null, null);
                AddVoca(12, "expand", "(시간•노력 등을) 쓰다, 들이다", null, null);
                AddVoca(12, "facility", "재능, 소질", "기능, 특징", "시설");
                AddVoca(12, "genre", "유형", null, null);
                AddVoca(12, "illustrate", "묘사하다", null, null);
                AddVoca(12, "infrastructure", "기반, 하부 구조", null, null);
                AddVoca(12, "inhibit", "억제하다; 금지하다", null, null);
                AddVoca(12, "involve", "~을 수반하다", null, null);
                AddVoca(12, "lease", "임차하다", null, null);
                AddVoca(12, "likewise", "또한; 마찬가지로", null, null);
                AddVoca(12, "limited", "제한된", null, null);
                AddVoca(12, "lodge in", "박다, 꽂아 넣다", null, null);
                AddVoca(12, "mingle", "섞이다, 혼합되다", null, null);
                AddVoca(12, "obligation", "의무", null, null);
                AddVoca(12, "oblige", "강요하다", null, null);
                AddVoca(12, "offer", "제공하다, 제안하다", null, null);
                AddVoca(12, "on occasion", "가끔", null, null);
                AddVoca(12, "pare", "껍질을 벗기다; 삭감하다", null, null);
                AddVoca(12, "predominately", "주로", null, null);
                AddVoca(12, "preordained", "예정된", null, null);
                AddVoca(12, "render", "~가 되게 하다", "주다", "~을 표현하다");
                AddVoca(12, "renown", "명성", null, null);
                AddVoca(12, "repel", "물리치다", null, null);
                AddVoca(12, "sanitation", "공중위생", null, null);
                AddVoca(12, "scorching", "몹시 뜨거운(더운)", null, null);
                AddVoca(12, "secluded", "외딴", null, null);
                AddVoca(12, "spare", "절약하다", "주다, (시간을) 할애하다", null);
                AddVoca(12, "stimulating", "활기(자극)를 주는", null, null);
                AddVoca(12, "typify", "대표하다, 특징을 나타내다", null, null);
                AddVoca(12, "wholesale", "대규모의", "도매의", null);
                AddVoca(13, "admire", "존경하다", null, null);
                AddVoca(13, "adroit", "능숙한", null, null);
                AddVoca(13, "ambivalent", "불확실한, 상반된 감정이 교차하는", null, null);
                AddVoca(13, "camouflag", "감추다, 위장하다", null, null);
                AddVoca(13, "composed", "차분한", "작성된", null);
                AddVoca(13, "conceal", "숨기다", null, null);
                AddVoca(13, "deliberate", "신중한", "의도적인", null);
                AddVoca(13, "exhilarate", "들뜨게 하다", null, null);
                AddVoca(13, "exposure", "폭로, 발각", null, null);
                AddVoca(13, "glow", "빛나다", null, null);
                AddVoca(13, "hiatus", "중단, 단절", null, null);
                AddVoca(13, "incinerate", "태우다", null, null);
                AddVoca(13, "ineffectively", "비효과적으로", null, null);
                AddVoca(13, "inert", "자동력이 없는, 움직일 수 없는", null, null);
                AddVoca(13, "luster", "광채", null, null);
                AddVoca(13, "massive", "거대한, 막대한", null, null);
                AddVoca(13, "occupy", "(주의•마음을) 끌다, 사로잡다", "차지하다, 사용하다", null);
                AddVoca(13, "precede", "앞서다, 우선하다", null, null);
                AddVoca(13, "prove", "입증하다", null, null);
                AddVoca(13, "purchase", "얻다, 획득하다", null, null);
                AddVoca(13, "restrict", "제한하다", null, null);
                AddVoca(13, "repture", "불화; 파열", "찢다, 파열시키다", null);
                AddVoca(13, "scrutiny", "정밀 조사", null, null);
                AddVoca(13, "seductive", "유혹적인", null, null);
                AddVoca(13, "seep", "스며들다", null, null);
                AddVoca(13, "segment", "부분", null, null);
                AddVoca(13, "shatter", "박살 내다", null, null);
                AddVoca(13, "shock", "충격을 주다, 놀라게 하다", null, null);
                AddVoca(13, "significant", "중요한", null, null);
                AddVoca(13, "slab", "조각", null, null);
                AddVoca(13, "slaughter", "학살하다", null, null);
                AddVoca(13, "strife", "싸움", null, null);
                AddVoca(13, "style", "방식", null, null);
                AddVoca(13, "sustained", "지속적인", null, null);
                AddVoca(13, "temperance", "자제, 절제", null, null);
                AddVoca(13, "tremendous", "엄청난", null, null);
                AddVoca(13, "vivid", "선명한; 생생한", null, null);
                AddVoca(13, "wedge", "억지로 밀어 넣다", null, null);
                AddVoca(14, "actually", "실제로", null, null);
                AddVoca(14, "adorn", "장식하다", null, null);
                AddVoca(14, "calculate", "추정하다, 어림잡다", null, null);
                AddVoca(14, "claim", "요구하다", null, null);
                AddVoca(14, "commemorate", "기념하다", null, null);
                AddVoca(14, "conformity", "일치", null, null);
                AddVoca(14, "copious", "풍부한", null, null);
                AddVoca(14, "desire", "열망하다; 요구하다", null, null);
                AddVoca(14, "diligently", "열심히", null, null);
                AddVoca(14, "enthrall", "매혹하다", null, null);
                AddVoca(14, "feast", "축제", "배불리 먹다", null);
                AddVoca(14, "gather", "모으다", null, null);
                AddVoca(14, "gauge", "평가하다, 판단하다", null, null);
                AddVoca(14, "glue", "접착시키다", null, null);
                AddVoca(14, "grand", "웅장한", null, null);
                AddVoca(14, "hearten", "격려하다", null, null);
                AddVoca(14, "hub", "중심", null, null);
                AddVoca(14, "hybrid", "잡종, 혼합물", null, null);
                AddVoca(14, "impetus", "자극", null, null);
                AddVoca(14, "improvise", "(연주•연설 등을) 즉흥적으로 하다", null, null);
                AddVoca(14, "irresistible", "매혹적인; 저항할 수 없는", null, null);
                AddVoca(14, "incised", "새겨진", null, null);
                AddVoca(14, "inherent in", "내재된", null, null);
                AddVoca(14, "juvenile", "어린", null, null);
                AddVoca(14, "main", "주요한", null, null);
                AddVoca(14, "negligence", "부주의, 태만", null, null);
                AddVoca(14, "outweigh", "~보다 뛰어나다", null, null);
                AddVoca(14, "pigment", "색소", null, null);
                AddVoca(14, "plausible", "그럴듯한", null, null);
                AddVoca(14, "prudent", "조심성 있는, 신중한", null, null);
                AddVoca(14, "revise", "수정하다", null, null);
                AddVoca(14, "spirit", "정신", null, null);
                AddVoca(14, "skillful", "숙련된", null, null);
                AddVoca(14, "tenet", "원칙", null, null);
                AddVoca(14, "transformation", "변화", null, null);
                AddVoca(14, "traverse", "가로지르다", null, null);
                AddVoca(14, "unbearbly", "극도로", null, null);
                AddVoca(14, "variable", "변하기 쉬운, 가변적인", null, null);
                AddVoca(14, "while", "~동안에; ~하는 한", "~할 지라도; ~와는 반대로", null);
                AddVoca(15, "affluent", "부유한, 풍족한", null, null);
                AddVoca(15, "aggravate", "악화시키다", null, null);
                AddVoca(15, "cling to", "달라붙다, 고수하다", null, null);
                AddVoca(15, "craft", "솜씨 있게 만들다", null, null);
                AddVoca(15, "crest", "정상", null, null);
                AddVoca(15, "critic", "비평가", null, null);
                AddVoca(15, "cross-hatching", "음영", null, null);
                AddVoca(15, "decimate", "많은 사람을 죽이다", null, null);
                AddVoca(15, "disciple", "제자", null, null);
                AddVoca(15, "disclose", "(사실 등을) 밝히다", null, null);
                AddVoca(15, "disposition", "성질, 기질", null, null);
                AddVoca(15, "dissimilar", "다른", null, null);
                AddVoca(15, "dominant", "우세한", null, null);
                AddVoca(15, "effect", "영향; 결과", null, null);
                AddVoca(15, "enhance", "향상시키다, 개선하다", null, null);
                AddVoca(15, "enunciate", "분명하게 발음하다", null, null);
                AddVoca(15, "eradicate", "근절하다", null, null);
                AddVoca(15, "harsh", "가혹한", null, null);
                AddVoca(15, "heritage", "전통, 유산", null, null);
                AddVoca(15, "inappropriate", "부적당한", null, null);
                AddVoca(15, "insolent", "무례한", null, null);
                AddVoca(15, "jeopardy", "위험", null, null);
                AddVoca(15, "luxury", "사치", null, null);
                AddVoca(15, "manipulate", "조종하다, 다루다", null, null);
                AddVoca(15, "mock", "조롱하다", null, null);
                AddVoca(15, "precious", "귀중한", null, null);
                AddVoca(15, "regard", "관심; 호감; 존경", null, null);
                AddVoca(15, "return", "되돌아가다", null, null);
                AddVoca(15, "set", "~을 놓다", null, null);
                AddVoca(15, "spacious", "넓은", null, null);
                AddVoca(15, "spectator", "구경꾼", null, null);
                AddVoca(15, "strict", "엄격한", null, null);
                AddVoca(15, "swift", "빠른", null, null);
                AddVoca(15, "synchronize", "동시에 일어나다", null, null);
                AddVoca(15, "throughout", "~의 도처에", null, null);
                AddVoca(15, "undermine", "약화시키다", null, null);
                AddVoca(15, "upset", "뒤엎다, 전복시키다", "당황하게 하다", null);
                AddVoca(15, "virtuous", "덕 있는", null, null);
                AddVoca(15, "wrangle", "논쟁하다; 말다툼하다", null, null);
                AddVoca(15, "withdraw", "물러나다", null, null);
                AddVoca(15, "worship", "숭배하다", null, null);
                AddVoca(16, "alternative", "대안", "대용이 되는", null);
                AddVoca(16, "analogous", "유사한", null, null);
                AddVoca(16, "annually", "매년", null, null);
                AddVoca(16, "awkward", "서투른", null, null);
                AddVoca(16, "capability", "재능", null, null);
                AddVoca(16, "cleanse", "깨끗이 하다", null, null);
                AddVoca(16, "collide", "충돌하다", null, null);
                AddVoca(16, "congested", "혼잡한", null, null);
                AddVoca(16, "contemporary", "현대의; 동시대의", null, null);
                AddVoca(16, "cover", "포함하다", null, null);
                AddVoca(16, "deceitful", "허위의", null, null);
                AddVoca(16, "exception", "제외", null, null);
                AddVoca(16, "feature", "특징", null, null);
                AddVoca(16, "fractious", "성미가 까다로운", null, null);
                AddVoca(16, "incorporate", "통합하다", null, null);
                AddVoca(16, "intimate", "친숙한", null, null);
                AddVoca(16, "invariably", "예외 없이, 반드시", null, null);
                AddVoca(16, "inveigle", "꾀다, 유혹하다", null, null);
                AddVoca(16, "lead", "단서", "야기하다", null);
                AddVoca(16, "loop", "묶다", null, null);
                AddVoca(16, "lucid", "명료한, 명쾌한", null, null);
                AddVoca(16, "master", "정통하다", null, null);
                AddVoca(16, "option", "선택", null, null);
                AddVoca(16, "paradoxical", "역설적인", null, null);
                AddVoca(16, "plumage", "깃털", null, null);
                AddVoca(16, "prevent", "~을 방해하다, 막다", null, null);
                AddVoca(16, "profuse", "풍부한", null, null);
                AddVoca(16, "revolve", "회전하다", null, null);
                AddVoca(16, "scale", "(기어)오르다", "정도, 단계", null);
                AddVoca(16, "scant", "부족한", "줄이다", null);
                AddVoca(16, "sensational", "세상을 들끓게 하는", null, null);
                AddVoca(16, "shallow", "얕은", null, null);
                AddVoca(16, "sort", "분류하다", "종류", null);
                AddVoca(16, "stylus", "첨필", null, null);
                AddVoca(16, "typically", "일반적으로", null, null);
                AddVoca(16, "vary", "다르다", null, null);
                AddVoca(16, "voracious", "만족할 줄 모르는, 탐욕적인", null, null);
                AddVoca(17, "absolute", "완전한, 절대적인", null, null);
                AddVoca(17, "adapted", "개조된", null, null);
                AddVoca(17, "chamber", "(작은) 방", null, null);
                AddVoca(17, "compact", "압축하다", "조밀한, 밀집한", null);
                AddVoca(17, "complacency", "만족", null, null);
                AddVoca(17, "compulsory", "강제적인", null, null);
                AddVoca(17, "concomitant", "동시에 일어나는", null, null);
                AddVoca(17, "condense", "압축(응축)하다", null, null);
                AddVoca(17, "conform", "순응하다, 따르다", null, null);
                AddVoca(17, "consistent", "모순이 없는, 일관된", null, null);
                AddVoca(17, "constrain", "억제하다", null, null);
                AddVoca(17, "contagious", "전염성 있는", null, null);
                AddVoca(17, "counterpart", "(동등한 자격의) 대응물", null, null);
                AddVoca(17, "debris", "잔해", null, null);
                AddVoca(17, "decisive", "결정적인", null, null);
                AddVoca(17, "disdain", "경멸하다", null, null);
                AddVoca(17, "element", "구성 요소", null, null);
                AddVoca(17, "erratic", "불규칙적인, 변덕스러운", null, null);
                AddVoca(17, "exhaust", "다 써버리다", "지치게 하다", null);
                AddVoca(17, "expand", "확장하다", null, null);
                AddVoca(17, "flattering", "아부하는", null, null);
                AddVoca(17, "full-blown", "성숙한", null, null);
                AddVoca(17, "henceforth", "앞으로, 차후", null, null);
                AddVoca(17, "inadvertently", "뜻하지 않게, 우연히", null, null);
                AddVoca(17, "intricate", "복잡한", null, null);
                AddVoca(17, "mammoth", "거대한", null, null);
                AddVoca(17, "merely", "단지", null, null);
                AddVoca(17, "ordinary", "보통의, 평범한", null, null);
                AddVoca(17, "plain", "분명한", "꾸밈없는, 간소한", null);
                AddVoca(17, "popular", "대중적인", null, null);
                AddVoca(17, "reconcile", "화해시키다, 조정하다", null, null);
                AddVoca(17, "reexamine", "재검토하다", null, null);
                AddVoca(17, "requirement", "조건, 조항", null, null);
                AddVoca(17, "revolutionize", "~에 혁명을 일으키다", null, null);
                AddVoca(17, "rival", "경쟁자", "경쟁하다", null);
                AddVoca(17, "shovel", "(삽으로) 파다", null, null);
                AddVoca(17, "succinct", "간결한", null, null);
                AddVoca(17, "shovel", "(삽으로) 파다", null, null);
                AddVoca(17, "succinct", "간결한", null, null);
                AddVoca(17, "tie", "관계", "묶다", null);
                AddVoca(18, "ability", "능력", null, null);
                AddVoca(18, "accessible", "이용 가능한, 접근하기 쉬운", null, null);
                AddVoca(18, "accord", "주다, 수여하다; 일치하다", null, null);
                AddVoca(18, "appear", "~인 듯하다, ~인 것 같이 보인다", null, null);
                AddVoca(18, "be rooted in", "~에 근거를 두다, ~에서 유래하다", null, null);
                AddVoca(18, "bog", "늪, 습지", null, null);
                AddVoca(18, "collaborate", "협력하다", null, null);
                AddVoca(18, "crucible", "도가니, 용광로", null, null);
                AddVoca(18, "crub", "제한(억제)하다", null, null);
                AddVoca(18, "cycle", "주기", null, null);
                AddVoca(18, "deem", "~라고 여기다", null, null);
                AddVoca(18, "devout", "독실한", null, null);
                AddVoca(18, "disperse", "흩어지게 하다", null, null);
                AddVoca(18, "economical", "절약하는", null, null);
                AddVoca(18, "eventually", "결국", null, null);
                AddVoca(18, "faint", "희미한", "기절하다", null);
                AddVoca(18, "financial", "재정상의", null, null);
                AddVoca(18, "frighten", "두렵게 하다", null, null);
                AddVoca(18, "geognosy", "지질학", null, null);
                AddVoca(18, "give way to", "물러가다, 양보하다", null, null);
                AddVoca(18, "immense", "거대한, 막대한", null, null);
                AddVoca(18, "impact", "영향", null, null);
                AddVoca(18, "ingenuity", "독창성, 창의력", null, null);
                AddVoca(18, "in keeping with", "~와 일치하여", null, null);
                AddVoca(18, "job", "일, 직무", null, null);
                AddVoca(18, "lethargic", "무기력한", null, null);
                AddVoca(18, "meager", "부족한", null, null);
                AddVoca(18, "parody", "풍자적 변형, 희화화", null, null);
                AddVoca(18, "refuge", "피난처, 은신처", null, null);
                AddVoca(18, "rural", "시골의", null, null);
                AddVoca(18, "scrub", "북북 문지르다", null, null);
                AddVoca(18, "secure", "확보하다", "안전한", null);
                AddVoca(18, "skepticism", "회의(론)", null, null);
                AddVoca(18, "so far", "지금까지", null, null);
                AddVoca(18, "spark", "야기하다", null, null);
                AddVoca(18, "speculation", "추측", null, null);
                AddVoca(18, "terrain", "지역", null, null);
                AddVoca(18, "tumult", "혼란, 소란", null, null);
                AddVoca(18, "unlimited", "무한한", null, null);
                AddVoca(18, "vagarious", "변덕스러운", null, null);
                AddVoca(18, "volume", "책", null, null);
                AddVoca(19, "advent", "출현", null, null);
                AddVoca(19, "article", "(개개의) 물품", null, null);
                AddVoca(19, "assembly", "의회", null, null);
                AddVoca(19, "associated", "연관된", null, null);
                AddVoca(19, "aware", "~을 알고 있는", null, null);
                AddVoca(19, "bank", "물가, 기슭", null, null);
                AddVoca(19, "by and large", "전반적으로, 대체로", null, null);
                AddVoca(19, "challenge", "난제", "도전하다, 물리치다", null);
                AddVoca(19, "compress", "압축하다", null, null);
                AddVoca(19, "consort", "교제하다", null, null);
                AddVoca(19, "construe", "해석하다", null, null);
                AddVoca(19, "correct", "고치다, 바로잡다", null, null);
                AddVoca(19, "curious", "호기심이 강한", null, null);
                AddVoca(19, "deadly", "치명적인", null, null);
                AddVoca(19, "defeated", "패배한", null, null);
                AddVoca(19, "deplete", "고갈시키다", null, null);
                AddVoca(19, "edge", "가장자리", null, null);
                AddVoca(19, "elude", "피하다", null, null);
                AddVoca(19, "endow", "부여하다", null, null);
                AddVoca(19, "exceedingly", "지나칠 정도로", null, null);
                AddVoca(19, "far-reaching", "방대한", null, null);
                AddVoca(19, "fluster", "혼란시키다", null, null);
                AddVoca(19, "guess", "추측하다", null, null);
                AddVoca(19, "importance", "중요함", null, null);
                AddVoca(19, "interfere", "방해하다, 간섭하다", null, null);
                AddVoca(19, "irksome", "지루한", null, null);
                AddVoca(19, "last", "마지막의", "지속하다", null);
                AddVoca(19, "manage", "관리하다", null, null);
                AddVoca(19, "mastery", "전문 기술, 숙달", null, null);
                AddVoca(19, "monopolize", "독점하다", null, null);
                AddVoca(19, "overcome", "이기다, 정복하다", null, null);
                AddVoca(19, "ratify", "승인하다", null, null);
                AddVoca(19, "replica", "복제", null, null);
                AddVoca(19, "shift", "옮기다, 바꾸다", null, null);
                AddVoca(19, "stride", "진보, 발전", null, null);
                AddVoca(19, "subject to", "(영향을) 받기 쉬운", null, null);
                AddVoca(19, "successive", "연속적인", null, null);
                AddVoca(19, "transition", "변화", null, null);
                AddVoca(19, "undertaking", "사업, 과제", null, null);
                AddVoca(20, "accurate", "정확한", null, null);
                AddVoca(20, "advisor", "고문, 자문역", null, null);
                AddVoca(20, "antagonize", "대항하다", null, null);
                AddVoca(20, "architecture", "구조", null, null);
                AddVoca(20, "assure", "확신시키다", null, null);
                AddVoca(20, "bond", "유대, 결속", null, null);
                AddVoca(20, "brave", "대담한", null, null);
                AddVoca(20, "crucial", "중대한", null, null);
                AddVoca(20, "complement", "보충, 보완", null, null);
                AddVoca(20, "comprise", "구성되다", null, null);
                AddVoca(20, "counter to", "~와 정반대로", null, null);
                AddVoca(20, "daring", "용감한", null, null);
                AddVoca(20, "devise", "고안하다", null, null);
                AddVoca(20, "duplicate", "복사(복제)하다", null, null);
                AddVoca(20, "dwindle", "줄다, 감소시키다", null, null);
                AddVoca(20, "embody", "구현하다", "~을 포함하다", null);
                AddVoca(20, "etch", "식각하다, 새기다", null, null);
                AddVoca(20, "flash", "번쩍이다", null, null);
                AddVoca(20, "imaginable", "상상할 수 있는", null, null);
                AddVoca(20, "infectious", "전염성의", null, null);
                AddVoca(20, "innumerable", "무수한", null, null);
                AddVoca(20, "invariable", "불변의", null, null);
                AddVoca(20, "meditate", "숙고하다, 깊이 생각하다", null, null);
                AddVoca(20, "opposite", "(성질•의미 등이) 정반대의", "정반대", null);
                AddVoca(20, "outdo", "~을 능가하다", null, null);
                AddVoca(20, "outline", "개요; 윤곽", null, null);
                AddVoca(20, "parallel", "~와 유사한, 평행의", "~에 필적하다", null);
                AddVoca(20, "preeminent", "탁월한", null, null);
                AddVoca(20, "reassuring", "용기를 북돋는", null, null);
                AddVoca(20, "regulate", "조절하다", null, null);
                AddVoca(20, "respectful", "공손한; 존경심을 보이는", null, null);
                AddVoca(20, "shrink", "줄어들다", null, null);
                AddVoca(20, "skill", "기술", null, null);
                AddVoca(20, "steadily", "지속적으로", null, null);
                AddVoca(20, "struggle", "싸우다", null, null);
                AddVoca(20, "subsequence", "이어서 일어나는 것", null, null);
                AddVoca(20, "warrant", "정당화하다", null, null);
                AddVoca(20, "ware", "제품", null, null);
                AddVoca(20, "yet", "그럼에도 불구하고", null, null);
                AddVoca(21, "abundance", "풍부함", null, null);
                AddVoca(21, "adaptability", "적응성, 융통성", null, null);
                AddVoca(21, "arrest", "체포하다", null, null);
                AddVoca(21, "assigned", "정해진", null, null);
                AddVoca(21, "be at odds with", "~와 불화하다", null, null);
                AddVoca(21, "curiously", "신기하게도", null, null);
                AddVoca(21, "dense", "짙은", null, null);
                AddVoca(21, "deploy", "(전략적으로) 배치하다", null, null);
                AddVoca(21, "discreet", "분별력 있는", null, null);
                AddVoca(21, "entire", "전체의", null, null);
                AddVoca(21, "evident", "분명한", null, null);
                AddVoca(21, "extensive", "넓은", null, null);
                AddVoca(21, "extinguish", "(불을) 끄다", "소멸시키다", null);
                AddVoca(21, "feeble", "연약한", null, null);
                AddVoca(21, "flavor", "특징", "맛, 풍미", null);
                AddVoca(21, "fragmentary", "단편적인", null, null);
                AddVoca(21, "in charge of", "~에 책임이 있는", null, null);
                AddVoca(21, "minor", "중요치 않은", null, null);
                AddVoca(21, "parcel out", "분할(분배)하다", null, null);
                AddVoca(21, "perceive", "알아차리다", null, null);
                AddVoca(21, "piece", "조각", "잇다, 접합하다", null);
                AddVoca(21, "pledge", "맹세", null, null);
                AddVoca(21, "portray", "묘사하다", null, null);
                AddVoca(21, "project", "계획", "돌출하다", null);
                AddVoca(21, "region", "지역", null, null);
                AddVoca(21, "safe", "안전한", null, null);
                AddVoca(21, "search", "탐색하다, 조사하다", null, null);
                AddVoca(21, "seethe", "(화가 나서) 속이 끓다", null, null);
                AddVoca(21, "shortcoming", "결점", null, null);
                AddVoca(21, "special", "특별한", null, null);
                AddVoca(21, "survey", "조사하다", null, null);
                AddVoca(21, "temperament", "성질", null, null);
                AddVoca(21, "tool", "도구", null, null);
                AddVoca(21, "uninitiated", "미숙한", null, null);
                AddVoca(21, "vanish", "사라지다", null, null);
                AddVoca(21, "vile", "사악한", null, null);
                AddVoca(21, "worldly", "세속적인", null, null);
                AddVoca(21, "wreck", "파괴하다", null, null);
                AddVoca(22, "accustomed", "익숙한", null, null);
                AddVoca(22, "allege", "주장하다, 우기다", null, null);
                AddVoca(22, "at the expense of", "~의 비용(대가)으로", null, null);
                AddVoca(22, "breed", "기르다", null, null);
                AddVoca(22, "chisel", "조각하다", null, null);
                AddVoca(22, "conclusive", "결정적인", null, null);
                AddVoca(22, "costly", "비싼", null, null);
                AddVoca(22, "crack down", "~을 엄히 단속하다", null, null);
                AddVoca(22, "degree", "정도", null, null);
                AddVoca(22, "delicate", "섬세한", null, null);
                AddVoca(22, "devote", "헌신하다", null, null);
                AddVoca(22, "die", "죽다", null, null);
                AddVoca(22, "distribute", "분배하다", null, null);
                AddVoca(22, "emergency", "위기, 위급", null, null);
                AddVoca(22, "fatal", "치명적인", null, null);
                AddVoca(22, "guilty", "유죄의", null, null);
                AddVoca(22, "hazard", "위험", null, null);
                AddVoca(22, "in any case", "여하간에, 여하튼", null, null);
                AddVoca(22, "incite", "자극하다", null, null);
                AddVoca(22, "moist", "축축한", null, null);
                AddVoca(22, "ornament", "장식하다", null, null);
                AddVoca(22, "peripheral", "주변의", null, null);
                AddVoca(22, "precipitous", "성급한", null, null);
                AddVoca(22, "primarily", "주로", "본래, 처음에", null);
                AddVoca(22, "primeval", "원시의", null, null);
                AddVoca(22, "raw", "가공하지 않은, 날것의", null, null);
                AddVoca(22, "reject", "거절하다", null, null);
                AddVoca(22, "replenish", "보충하다", null, null);
                AddVoca(22, "rot", "부패하다", null, null);
                AddVoca(22, "ruin", "파괴하다", "폐허", null);
                AddVoca(22, "runoff", "범람, 넘쳐흐름", null, null);
                AddVoca(22, "shorten", "줄이다", null, null);
                AddVoca(22, "spoil", "망치다, 손상시키다", null, null);
                AddVoca(22, "standard", "기준", "보통의", null);
                AddVoca(22, "stipulation", "조건", null, null);
                AddVoca(22, "strikingly", "두드러지게", null, null);
                AddVoca(22, "subtract", "빼다", null, null);
                AddVoca(22, "thaw", "녹다", null, null);
                AddVoca(22, "unpin", "핀(핀 종류의 것)을 빼다", null, null);
                AddVoca(23, "akin to", "~와 유사한, ~에 가까운", null, null);
                AddVoca(23, "appealing", "매력적인", null, null);
                AddVoca(23, "approach", "접근법, 방법", "접근하다", null);
                AddVoca(23, "argue", "논쟁하다", null, null);
                AddVoca(23, "assert", "주장하다", null, null);
                AddVoca(23, "brace", "받치다, 보강하다", null, null);
                AddVoca(23, "catastrophic", "비참한, 비극적인", null, null);
                AddVoca(23, "clarify", "명료하게 하다", null, null);
                AddVoca(23, "constantly", "지속적으로", null, null);
                AddVoca(23, "deception", "속임수, 사기", null, null);
                AddVoca(23, "distinct", "별개의", "뚜렷한", null);
                AddVoca(23, "edition", "(간행물)판", null, null);
                AddVoca(23, "elaborate", "복잡한, 정교한", null, null);
                AddVoca(23, "flaw", "결점", null, null);
                AddVoca(23, "flood", "범람시키다", null, null);
                AddVoca(23, "floods of", "다수의, 쇄도하는", null, null);
                AddVoca(23, "habitat", "거주지", null, null);
                AddVoca(23, "hint", "암시", null, null);
                AddVoca(23, "intensify", "강화하다", null, null);
                AddVoca(23, "intentional", "고의적인", null, null);
                AddVoca(23, "kin", "친척", null, null);
                AddVoca(23, "make one's way", "나아가다", null, null);
                AddVoca(23, "measure", "측정하다", null, null);
                AddVoca(23, "minute", "미세한; 정밀한", null, null);
                AddVoca(23, "notwithstanding", "~에도 불구하고", null, null);
                AddVoca(23, "profound", "깊은, 심오한", null, null);
                AddVoca(23, "protect", "보호하다", null, null);
                AddVoca(23, "receive", "받다, 얻다", null, null);
                AddVoca(23, "relevance", "적절, 타당성; 관련성", null, null);
                AddVoca(23, "reliance", "의존", null, null);
                AddVoca(23, "represent", "묘사하다, 표현하다", "대표하다", null);
                AddVoca(23, "require", "요구하다", null, null);
                AddVoca(23, "resemble", "닮다", null, null);
                AddVoca(23, "resolve", "결정하다", "해결하다", null);
                AddVoca(23, "retard", "지체시키다", null, null);
                AddVoca(23, "roster", "명부", null, null);
                AddVoca(23, "scenic", "풍경이 아름다운", null, null);
                AddVoca(24, "absurd", "불합리한", "어리석은", null);
                AddVoca(24, "activity", "활기", null, null);
                AddVoca(24, "assort", "분류하다", null, null);
                AddVoca(24, "beam", "빛나다", null, null);
                AddVoca(24, "break", "부수다", "(짧은) 휴식", null);
                AddVoca(24, "bromide", "진부한(낡은) 말(생각)", null, null);
                AddVoca(24, "common", "공통의", null, null);
                AddVoca(24, "consciously", "의도적으로", null, null);
                AddVoca(24, "context", "배경", null, null);
                AddVoca(24, "damage", "손상, 손해", null, null);
                AddVoca(24, "detach", "분리하다, 떼다", null, null);
                AddVoca(24, "dormant", "활동하지 않는", null, null);
                AddVoca(24, "environment", "환경", null, null);
                AddVoca(24, "essential", "필수적인", null, null);
                AddVoca(24, "heighten", "늘리다", null, null);
                AddVoca(24, "hinder", "방해하다", null, null);
                AddVoca(24, "impose", "강요하다", null, null);
                AddVoca(24, "ingenious", "독창적인", null, null);
                AddVoca(24, "insignificant", "사소한", null, null);
                AddVoca(24, "keen", "예리한", null, null);
                AddVoca(24, "lodge", "거처(피난처)를 제공하다", "숙박하다", null);
                AddVoca(24, "power", "영향력, 힘", null, null);
                AddVoca(24, "prominent", "눈에 띄는, 탁월한", null, null);
                AddVoca(24, "provided", "만약 ~이라면", null, null);
                AddVoca(24, "put together", "결합시키다", null, null);
                AddVoca(24, "reflect", "숙고하다, 깊이 생각하다", "반영하다, 나타내다", null);
                AddVoca(24, "relinquish", "포기하다, 버리다", null, null);
                AddVoca(24, "representative", "전형적인", null, null);
                AddVoca(24, "scan", "조사하다", null, null);
                AddVoca(24, "sever", "절단하다, 분리하다", null, null);
                AddVoca(24, "shortly", "곧", null, null);
                AddVoca(24, "showcase", "전시하다", null, null);
                AddVoca(24, "succession", "연속", null, null);
                AddVoca(24, "summit", "정상", null, null);
                AddVoca(24, "token", "상징, 표시", null, null);
                AddVoca(24, "transmit", "전달하다", null, null);
                AddVoca(24, "useful", "유익한, 도움이 되는", null, null);
                AddVoca(24, "vestige", "흔적", null, null);
                AddVoca(25, "aim", "목표하다", "목적", null);
                AddVoca(25, "allocate", "책정하다; 배분하다", null, null);
                AddVoca(25, "attribute to", "~에서 기인한, ~로 설명되는", null, null);
                AddVoca(25, "authenticate", "입증하다, 증명하다", null, null);
                AddVoca(25, "confuse", "혼란시키다", null, null);
                AddVoca(25, "debate", "논쟁", null, null);
                AddVoca(25, "detractor", "험담하는 사람", null, null);
                AddVoca(25, "disguise", "속이다, 감추다", "위장", null);
                AddVoca(25, "dissent", "의견을 달리하다", null, null);
                AddVoca(25, "distinguish", "구별하다", null, null);
                AddVoca(25, "draw", "끌다", null, null);
                AddVoca(25, "drawback", "결점", null, null);
                AddVoca(25, "dye", "염료, 물감", null, null);
                AddVoca(25, "emit", "발신하다", null, null);
                AddVoca(25, "expose", "드러내다", null, null);
                AddVoca(25, "flawless", "흠 없는", null, null);
                AddVoca(25, "frustrate", "좌절시키다", null, null);
                AddVoca(25, "full", "완전한", "상세한", null);
                AddVoca(25, "indicate", "넌지시 비추다", null, null);
                AddVoca(25, "initially", "처음에", null, null);
                AddVoca(25, "innovative", "기발한, 혁신적인", null, null);
                AddVoca(25, "landslide", "산사태", null, null);
                AddVoca(25, "malady", "질병", null, null);
                AddVoca(25, "minimize", "줄이다", "과소평가하다", null);
                AddVoca(25, "order", "명령", "질서, 조화", null);
                AddVoca(25, "prohibit", "금지하다", null, null);
                AddVoca(25, "reduce", "감소시키다", null, null);
                AddVoca(25, "reveal", "드러내다", null, null);
                AddVoca(25, "shed light on", "~을 명백히 하다", null, null);
                AddVoca(25, "sink", "가라앉다", null, null);
                AddVoca(25, "size", "크기", null, null);
                AddVoca(25, "slope", "경사", null, null);
                AddVoca(25, "subside", "진정되다", null, null);
                AddVoca(25, "take place", "발생하다", null, null);
                AddVoca(25, "though", "그러나", "~이지만, 비록 ~일지라도", null);
                AddVoca(25, "underground", "비밀의", null, null);
                AddVoca(26, "antipathy", "반감", null, null);
                AddVoca(26, "applicable", "적용 가능한, 적절한", null, null);
                AddVoca(26, "blot out", "가리다", null, null);
                AddVoca(26, "bold", "대담한", null, null);
                AddVoca(26, "boom", "번성하다", null, null);
                AddVoca(26, "characteristic", "독특한", "특성", null);
                AddVoca(26, "clear", "명쾌한", null, null);
                AddVoca(26, "coarse", "거친, 천한", null, null);
                AddVoca(26, "concentrate", "집중하다", "모으다", null);
                AddVoca(26, "contemplate", "심사숙고하다", null, null);
                AddVoca(26, "cripple", "손상시키다", null, null);
                AddVoca(26, "demanding", "힘든, 큰 노력을 요하는", null, null);
                AddVoca(26, "deviate", "벗어나다", null, null);
                AddVoca(26, "discover", "확인하다, 찾아내다", null, null);
                AddVoca(26, "discrete", "구별되는", null, null);
                AddVoca(26, "encompass", "포함하다", null, null);
                AddVoca(26, "entertain", "즐겁게 하다", null, null);
                AddVoca(26, "far-sighted", "현명한", null, null);
                AddVoca(26, "fluctuate", "변동하다", null, null);
                AddVoca(26, "halt", "멈추다", null, null);
                AddVoca(26, "incessantly", "끊임없이", null, null);
                AddVoca(26, "leading", "우세한, 주된", null, null);
                AddVoca(26, "modify", "변경하다", null, null);
                AddVoca(26, "mutation", "변이, 변화", null, null);
                AddVoca(26, "obelisk", "방첨탑, 오벨리스크", null, null);
                AddVoca(26, "pastime", "기분 전환", null, null);
                AddVoca(26, "rather than", "~대신에", null, null);
                AddVoca(26, "receptacle", "그릇, 용기", null, null);
                AddVoca(26, "rely", "의지하다", null, null);
                AddVoca(26, "remote", "외딴, 멀리 떨어진", null, null);
                AddVoca(26, "rotten", "썩은, 부패한", null, null);
                AddVoca(26, "rove", "배회하다", null, null);
                AddVoca(26, "shoddy", "조악한, (질이) 떨어지는", null, null);
                AddVoca(26, "shred", "(갈기갈기) 찢다", null, null);
                AddVoca(26, "simply", "단지", null, null);
                AddVoca(26, "span", "기간", "~에 걸치다, 이르다", null);
                AddVoca(26, "stun", "놀라게 하다", null, null);
                AddVoca(26, "tranquil", "평온한, 차분한", null, null);
                AddVoca(27, "assistance", "원조", null, null);
                AddVoca(27, "avoid", "~을 피하다", null, null);
                AddVoca(27, "best-suited", "가장 적절한", null, null);
                AddVoca(27, "bridle", "굴레", null, null);
                AddVoca(27, "classify", "분류하다", null, null);
                AddVoca(27, "collectively", "공동으로", null, null);
                AddVoca(27, "comparable", "유사한", null, null);
                AddVoca(27, "cultivator", "경작자", null, null);
                AddVoca(27, "designated", "지정된", null, null);
                AddVoca(27, "detrimental", "해로운, 불리한", null, null);
                AddVoca(27, "differentiate", "구별하다", null, null);
                AddVoca(27, "display", "보여 주다", null, null);
                AddVoca(27, "emissary", "사절, 특사", null, null);
                AddVoca(27, "enact", "제정하다", null, null);
                AddVoca(27, "evenly", "고르게, 일관되게", null, null);
                AddVoca(27, "expedience", "편의", null, null);
                AddVoca(27, "genuinely", "정말로", null, null);
                AddVoca(27, "immediately", "즉시, 당장", null, null);
                AddVoca(27, "important", "중요한", null, null);
                AddVoca(27, "inconceivable", "상상도 못할", null, null);
                AddVoca(27, "in progress", "진행 중인", null, null);
                AddVoca(27, "it followed that ~", "그 결과로서 ~가 되었다", null, null);
                AddVoca(27, "keep in touch", "연락을 유지하다", null, null);
                AddVoca(27, "massacre", "대량학살", null, null);
                AddVoca(27, "mean", "~을 의미하다", "비열한", "중간의");
                AddVoca(27, "mute", "무언의", null, null);
                AddVoca(27, "participate", "함께 하다", null, null);
                AddVoca(27, "pit", "(사람•기술 등을) ~와 대항시키다", "구멍", null);
                AddVoca(27, "raise", "올리다", null, null);
                AddVoca(27, "rare", "드문", null, null);
                AddVoca(27, "respectively", "각각", null, null);
                AddVoca(27, "seemingly", "보기에", null, null);
                AddVoca(27, "sporadically", "때때로, 간헐적으로", null, null);
                AddVoca(27, "stringent", "엄한", null, null);
                AddVoca(27, "superficial", "외면의", null, null);
                AddVoca(27, "timid", "소심한", null, null);
                AddVoca(27, "transport", "운송하다", null, null);
                AddVoca(27, "unavoidable", "불가피한", null, null);
                AddVoca(27, "uniform", "일관성 있는", null, null);
                AddVoca(27, "unsubstantial", "비현실적인", "내용이 없는", null);
                AddVoca(28, "aptly", "적절히", null, null);
                AddVoca(28, "attract", "(마음을) 끌다", null, null);
                AddVoca(28, "beverage", "음료수", null, null);
                AddVoca(28, "blunt", "무딘", null, null);
                AddVoca(28, "bustling", "부산한", null, null);
                AddVoca(28, "control", "지배하다", null, null);
                AddVoca(28, "controversy", "논쟁", null, null);
                AddVoca(28, "dichotomy", "양분, 이분", null, null);
                AddVoca(28, "disruption", "중단", null, null);
                AddVoca(28, "enthusiasm", "열정", null, null);
                AddVoca(28, "episode", "하나의 사건", null, null);
                AddVoca(28, "equivalent", "동등한", null, null);
                AddVoca(28, "evoke", "일깨우다, 자아내다", null, null);
                AddVoca(28, "exotic", "기묘한, 못 보던", null, null);
                AddVoca(28, "flair", "재주, 재능", null, null);
                AddVoca(28, "flight", "탈출", null, null);
                AddVoca(28, "formidable", "무서운", null, null);
                AddVoca(28, "frugal", "절약하는", null, null);
                AddVoca(28, "fuel", "지지하다, 자극하다", "연료", null);
                AddVoca(28, "game", "사냥감", null, null);
                AddVoca(28, "hand in hand", "협력하여, 동반하여", null, null);
                AddVoca(28, "intermittent", "간헐적인", null, null);
                AddVoca(28, "intersect", "교차하다, 가로지르다", null, null);
                AddVoca(28, "make sense", "이치에 맞다", null, null);
                AddVoca(28, "movement", "(정치•사회적) 운동", null, null);
                AddVoca(28, "pass through", "꿰뚫다", null, null);
                AddVoca(28, "precise", "정확한", null, null);
                AddVoca(28, "publish", "발표하다", null, null);
                AddVoca(28, "readily", "쉽게; 기꺼이", null, null);
                AddVoca(28, "record", "기록", null, null);
                AddVoca(28, "relieve", "경감하다", null, null);
                AddVoca(28, "settle down", "진정시키다", null, null);
                AddVoca(28, "shun", "피하다", null, null);
                AddVoca(28, "spectacular", "멋진, 장엄한", null, null);
                AddVoca(28, "steady", "안정된", null, null);
                AddVoca(28, "store", "따로 떼어두다, 비축하다", null, null);
                AddVoca(28, "stupid", "어리석은", null, null);
                AddVoca(28, "success", "성공, 달성", null, null);
                AddVoca(28, "tend", "돌보다", null, null);
                AddVoca(28, "wattle", "가는 막대기", null, null);
                AddVoca(28, "wrath", "분노", null, null);
                AddVoca(29, "acid", "신랄한", "산성의", null);
                AddVoca(29, "amass", "모으다", null, null);
                AddVoca(29, "breakthrough", "약진, 큰 발전", null, null);
                AddVoca(29, "cause", "야기시키다, 초래하다", null, null);
                AddVoca(29, "certain", "일정한", null, null);
                AddVoca(29, "component", "성분", null, null);
                AddVoca(29, "conditional", "조건부의, ~여하에 달린", null, null);
                AddVoca(29, "confront", "직면하다", null, null);
                AddVoca(29, "consequence", "결과", null, null);
                AddVoca(29, "crack", "쪼개다, 깨뜨리다", null, null);
                AddVoca(29, "crude", "천연 그대로의, 가공하지 않은", null, null);
                AddVoca(29, "drought", "가뭄", null, null);
                AddVoca(29, "effort", "노력", null, null);
                AddVoca(29, "emerge", "나타나다", null, null);
                AddVoca(29, "endurance", "인내; 내구력", null, null);
                AddVoca(29, "euphoria", "행복감", null, null);
                AddVoca(29, "exacerbate", "더욱 심하게 하다", null, null);
                AddVoca(29, "explain", "설명하다", null, null);
                AddVoca(29, "finish", "끝내다", null, null);
                AddVoca(29, "hollow", "텅 빈", null, null);
                AddVoca(29, "lash", "묶다, 매다", null, null);
                AddVoca(29, "leisurely", "느긋한", null, null);
                AddVoca(29, "manageable", "관리할 수 있는, 감당할 수 있는", null, null);
                AddVoca(29, "note", "명성", null, null);
                AddVoca(29, "periphery", "주변부", null, null);
                AddVoca(29, "practical", "실용적인", null, null);
                AddVoca(29, "prerequisite", "필요조건", null, null);
                AddVoca(29, "relatively", "비교적으로", null, null);
                AddVoca(29, "rudimentary", "기본적인, 기초적인", null, null);
                AddVoca(29, "selected", "선택된", null, null);
                AddVoca(29, "shed", "탈피하다", "(빛 등을) 비추다", null);
                AddVoca(29, "spotty", "고르지 않은", null, null);
                AddVoca(29, "spread", "퍼지다, ~에 이르다", null, null);
                AddVoca(29, "staunch", "확고한, 충실한", null, null);
                AddVoca(29, "stress", "강조", "강조하다", null);
                AddVoca(29, "stunted", "(성장이) 멎은", null, null);
                AddVoca(29, "trespass", "침해하다", null, null);
                AddVoca(29, "trumpet", "공표하다", null, null);
                AddVoca(29, "via", "~을 통하여", null, null);
                AddVoca(30, "accumulate", "모으다", null, null);
                AddVoca(30, "antithesis", "정반대", null, null);
                AddVoca(30, "astute", "기민한", null, null);
                AddVoca(30, "be up to", "~에 달려 있다", null, null);
                AddVoca(30, "being", "생물", null, null);
                AddVoca(30, "bring about", "초래하다", null, null);
                AddVoca(30, "cache", "은닉처", null, null);
                AddVoca(30, "celebratory", "축하의, 축하하는", null, null);
                AddVoca(30, "close", "면밀한", "차단하다", null);
                AddVoca(30, "cognitive", "정신적인, 인식의", null, null);
                AddVoca(30, "create", "만들어내다", null, null);
                AddVoca(30, "destroy", "파괴하다, 망치다", null, null);
                AddVoca(30, "diminutive", "작은", null, null);
                AddVoca(30, "endangered", "멸종위기에 처한, 위험에 처한", null, null);
                AddVoca(30, "formative", "형성되는, 발달의", null, null);
                AddVoca(30, "founder", "실패하다", null, null);
                AddVoca(30, "glean", "모으다", null, null);
                AddVoca(30, "govern", "지배하다", "통제하다", null);
                AddVoca(30, "indigenous", "토착의", null, null);
                AddVoca(30, "integrate", "통합하다", null, null);
                AddVoca(30, "interval", "(시간•거리의) 간격", null, null);
                AddVoca(30, "largely", "대개", null, null);
                AddVoca(30, "magnificent", "굉장히 멋진", null, null);
                AddVoca(30, "overshadow", "가리다, 어둡게 하다", null, null);
                AddVoca(30, "particular", "특별한", null, null);
                AddVoca(30, "ramification", "결과", null, null);
                AddVoca(30, "rather", "약간, 다소", null, null);
                AddVoca(30, "realm", "범위, 영역", null, null);
                AddVoca(30, "rivalry", "경쟁", null, null);
                AddVoca(30, "silent", "말이 없는", null, null);
                AddVoca(30, "situate", "위치시키다", null, null);
                AddVoca(30, "sphere", "분야", null, null);
                AddVoca(30, "stealthily", "은밀히, 몰래", null, null);
                AddVoca(30, "superb", "뛰어난, 훌륭한", null, null);
                AddVoca(30, "swell", "(크기•수량 등이) 증가하다", null, null);
                AddVoca(30, "tender", "부드러운", "변상금", null);
                AddVoca(30, "velocity", "속도, 신속함", null, null);
                AddVoca(30, "wild", "야생의", "난폭한", null);

                // 스페셜 단어 추가 (TOEIC용 단어)
                AddVoca(61, "addition", "추가", null, null);
                AddVoca(61, "extension", "연장", null, null);
                AddVoca(61, "competitiveness", "경쟁력", null, null);
                AddVoca(61, "productivity", "생산성", null, null);
                AddVoca(61, "preference", "선호", null, null);
                AddVoca(61, "payment", "납부", null, null);
                AddVoca(61, "analysis", "분석", null, null);
                AddVoca(61, "growth", "성장", null, null);
                AddVoca(61, "enthusiasm", "열의", null, null);
                AddVoca(61, "approval", "승인", null, null);
                AddVoca(61, "disposal", "처분", null, null);
                AddVoca(61, "removal", "제거", null, null);
                AddVoca(61, "renewal", "갱신", null, null);
                AddVoca(61, "arrival", "도착", null, null);
                AddVoca(61, "appraisal", "평가", null, null);
                AddVoca(61, "proposal", "제안", null, null);
                AddVoca(61, "potential", "잠재력", null, null);
                AddVoca(61, "individual", "개인", null, null);
                AddVoca(61, "professional", "전문가", null, null);
                AddVoca(61, "alternative", "대안(책)", null, null);
                AddVoca(61, "representative", "대표자", null, null);
                AddVoca(61, "objective", "목적", null, null);
                AddVoca(61, "executive", "중역", null, null);
                AddVoca(61, "initiative", "계획", null, null);
                AddVoca(61, "perspective", "관점", null, null);
                AddVoca(61, "planning", "계획 수립", null, null);
                AddVoca(61, "accounting", "회계", null, null);
                AddVoca(61, "funding", "자금(재정) 지원", null, null);
                AddVoca(61, "dining", "식사", null, null);
                AddVoca(61, "opening", "공석, 개막식", null, null);
                AddVoca(61, "training", "훈련", null, null);
                AddVoca(61, "marketing", "마케팅", null, null);
                AddVoca(61, "spending", "지출", null, null);
                AddVoca(61, "understanding", "이해", null, null);
                AddVoca(61, "boarding", "탑승", null, null);
                AddVoca(61, "housing", "주택", null, null);
                AddVoca(61, "widening", "확장", null, null);
                AddVoca(61, "remainder", "나머지", null, null);
                AddVoca(61, "architect", "건축가", null, null);
                AddVoca(61, "critic", "비평가", null, null);
                AddVoca(61, "characteristic", "특성", null, null);
                AddVoca(61, "assembly", "조립", null, null);
                AddVoca(61, "delegate", "대표자", null, null);
                AddVoca(61, "access", "접근, 이용, 접근하다, 이용하다", null, null);
                AddVoca(61, "change", "변화, 변화하다", null, null);
                AddVoca(61, "demand", "수요, 요구하다", null, null);
                AddVoca(61, "estimate", "견적, 견적내다", null, null);
                AddVoca(61, "experience", "경험, 경험하다", null, null);
                AddVoca(61, "function", "기능, 기능하다", null, null);
                AddVoca(61, "increase", "증가, 증가하다", null, null);
                AddVoca(61, "manufacture", "제조, 제조하다", null, null);
                AddVoca(61, "need", "필요, 필요로 하다", null, null);
                AddVoca(61, "offer", "제안, 제안하다", null, null);
                AddVoca(61, "purchase", "구입, 구입하다", null, null);
                AddVoca(61, "research", "연구, 연구하다", null, null);
                AddVoca(61, "request", "요청, 요청하다", null, null);
                AddVoca(61, "review", "검토, 검토하다", null, null);
                AddVoca(61, "stay", "체류, 체류하다", null, null);
                AddVoca(61, "support", "지원, 지원하다", null, null);
                AddVoca(61, "visit", "방문, 방문하다", null, null);
                AddVoca(61, "work", "일, 일하다", null, null);
                AddVoca(62, "information", "정보 (불가산)", null, null);
                AddVoca(62, "knowledge", "지식 (불가산)", null, null);
                AddVoca(62, "advice", "충고 (불가산)", null, null);
                AddVoca(62, "access", "접근 (불가산)", null, null);
                AddVoca(62, "money", "돈 (불가산)", null, null);
                AddVoca(62, "cash", "현금 (불가산)", null, null);
                AddVoca(62, "approval", "승인 (불가산)", null, null);
                AddVoca(62, "consent", "허가 (불가산)", null, null);
                AddVoca(62, "assistance", "보조 (불가산)", null, null);
                AddVoca(62, "potential", "잠재력 (불가산)", null, null);
                AddVoca(62, "equipment", "장비 (불가산)", null, null);
                AddVoca(62, "baggage", "수하물 (불가산)", null, null);
                AddVoca(62, "luggage", "수하물 (불가산)", null, null);
                AddVoca(62, "clothing", "의류 (불가산)", null, null);
                AddVoca(62, "furniture", "가구 (불가산)", null, null);
                AddVoca(62, "stationery", "문구류 (불가산)", null, null);
                AddVoca(62, "merchandise", "상품 (불가산)", null, null);
                AddVoca(62, "representative", "대표자 (가산)", "직원 (가산)", null);
                AddVoca(62, "employee", "직원 (가산)", null, null);
                AddVoca(62, "official", "공무원 (가산)", null, null);
                AddVoca(62, "applicant", "지원자 (가산)", null, null);
                AddVoca(62, "attendant", "참석자 (가산)", null, null);
                AddVoca(62, "discount", "할인 (가산)", null, null);
                AddVoca(62, "sale", "할인 (가산)", null, null);
                AddVoca(62, "refund", "환불 (가산)", null, null);
                AddVoca(62, "price", "가격 (가산)", null, null);
                AddVoca(62, "rate", "요금 (가산)", null, null);
                AddVoca(62, "bonus", "보너스 (가산)", null, null);
                AddVoca(62, "salary", "급여 (가산)", null, null);
                AddVoca(62, "account", "계좌 (가산)", null, null);
                AddVoca(62, "increase", "증가 (가산)", null, null);
                AddVoca(62, "reduction", "감소 (가산)", null, null);
                AddVoca(62, "change", "변화 (가산)", null, null);
                AddVoca(62, "place", "장소 (가산)", null, null);
                AddVoca(62, "request", "요청(사항) (가산)", null, null);
                AddVoca(62, "complaint", "불만(사항) (가산)", null, null);
                AddVoca(62, "decision", "결정 (가산)", null, null);
                AddVoca(62, "benefit", "혜택 (가산)", null, null);
                AddVoca(62, "reservation", "예약 (가산)", null, null);
                AddVoca(62, "arrangement", "준비 (가산)", null, null);
                AddVoca(62, "resource", "자원 (가산)", null, null);
                AddVoca(62, "regulations", "규정 (주로 복수 가산)", null, null);
                AddVoca(62, "precautions", "예방 조치 (주로 복수 가산)", null, null);
                AddVoca(62, "instructions", "지시 사항 (주로 복수 가산)", null, null);
                AddVoca(62, "guidelines", "지침 (주로 복수 가산)", null, null);
                AddVoca(62, "standards", "기준 (주로 복수 가산)", null, null);
                AddVoca(62, "procedures", "절차 (주로 복수 가산)", null, null);
                AddVoca(62, "measures", "조치 (주로 복수 가산)", null, null);
                AddVoca(62, "belongings", "소지품 (주로 복수 가산)", null, null);
                AddVoca(62, "goods", "상품 (주로 복수 가산)", null, null);
                AddVoca(62, "valuables", "귀중품 (주로 복수 가산)", null, null);
                AddVoca(62, "earnings", "수익 (주로 복수 가산)", null, null);




                // 부연설명 테이블 추가
                db.Open();
                tableCommand = "CREATE TABLE IF NOT EXISTS Explanations (" +
                    "Day INTEGER PRIMARY KEY, " +
                    "Explanation NVARCHAR(128) NOT NULL)";

                createTable = new SqliteCommand(tableCommand, db);
                createTable.ExecuteReader();
                db.Close();

                // 설명 추가
                AddExplanation(61, "명사의 형태 및 동사와 형태가 동일한 명사");
                AddExplanation(62, "가산명사와 불가산명사");
                AddExplanation(63, "사람명사(=가산)와 사물/추상명사");
                AddExplanation(64, "의미가 비슷한 가산/불가산명사");
            }
        }

        private static void AddVoca(int day, string eng, string kor1, string kor2, string kor3)
        {
            using (SqliteConnection db = new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                string insertCommand = "INSERT INTO Vocabularies(Day, Eng, Kor1, Kor2, Kor3) SELECT @Day, @Eng, @Kor1, @Kor2, @Kor3 " +
                    "WHERE NOT EXISTS (SELECT Eng FROM Vocabularies WHERE Eng=@Eng);";

                SqliteCommand insertVoca = new SqliteCommand(insertCommand, db);

                insertVoca.Parameters.AddWithValue("@Day", day);
                insertVoca.Parameters.AddWithValue("@Eng", eng);
                insertVoca.Parameters.AddWithValue("@Kor1", kor1);
                if (kor2 == null) insertVoca.Parameters.AddWithValue("@Kor2", DBNull.Value);
                else insertVoca.Parameters.AddWithValue("@Kor2", kor2);
                if (kor3 == null) insertVoca.Parameters.AddWithValue("@Kor3", DBNull.Value);
                else insertVoca.Parameters.AddWithValue("@Kor3", kor3);

                insertVoca.ExecuteReader();

                db.Close();
            }
        }

        private static void AddExplanation(int day, string explanation)
        {
            using (SqliteConnection db = new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                string insertCommand = "INSERT INTO Explanations SELECT @Day, @Explanation " +
                    "WHERE NOT EXISTS (SELECT Day FROM Explanations WHERE Day=@Day);";

                SqliteCommand insertVoca = new SqliteCommand(insertCommand, db);

                insertVoca.Parameters.AddWithValue("@Day", day);
                insertVoca.Parameters.AddWithValue("@Explanation", explanation);

                insertVoca.ExecuteReader();

                db.Close();
            }
        }

        // 데이터베이스 범용 검색 함수
        public static List<string> GetData()
        {
            List<string> entries = new List<string>();

            using (SqliteConnection db =
                new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                SqliteCommand selectCommand = new SqliteCommand("SELECT * from Vocabularies", db);

                SqliteDataReader query = selectCommand.ExecuteReader();

                while (query.Read())
                {
                    entries.Add(query.GetString(0));
                }

                db.Close();
            }

            return entries;
        }

        public static List<List<string>> GetVoca(int day)
        {
            List<List<string>> entries = new List<List<string>>();
            List<string> record = null;

            using (SqliteConnection db = new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                SqliteCommand selectCommand = new SqliteCommand("SELECT * FROM Vocabularies WHERE Day = @Day", db);
                selectCommand.Parameters.AddWithValue("@Day", day);

                SqliteDataReader query = selectCommand.ExecuteReader();

                while (query.Read())
                {
                    record = new List<string>();
                    record.Add(query.GetString(2));
                    record.Add(query.GetString(3));
                    if (query.IsDBNull(4)) record.Add(null);
                    else record.Add(query.GetString(4));
                    if (query.IsDBNull(5)) record.Add(null);
                    else record.Add(query.GetString(5));

                    entries.Add(record);
                }

                db.Close();
            }

            return entries;
        }

        public static string GetExplanation(int day)
        {
            string result = "";

            using (SqliteConnection db =
                new SqliteConnection("Filename=hackersVoca2006.db"))
            {
                db.Open();

                SqliteCommand selectCommand = new SqliteCommand("SELECT Explanation from Explanations WHERE Day = @Day", db);
                selectCommand.Parameters.AddWithValue("@Day", day);

                SqliteDataReader query = selectCommand.ExecuteReader();

                while (query.Read())
                {
                    result = query.GetString(0);
                }

                db.Close();
            }

            return result;
        }
    }
}
